// Code generated by command: go run gen.go -out ../internal/functions/accel_avx2_amd64.s -stubs ../internal/functions/accel_avx2_amd64.go -pkg functions. DO NOT EDIT.

#include "textflag.h"

// func VecMul_AVX2_I64(x []uint64, y []uint64)
// Requires: AVX, AVX2
TEXT ·VecMul_AVX2_I64(SB), NOSPLIT, $0-48
	MOVQ     x_base+0(FP), DI
	MOVQ     y_base+24(FP), SI
	VMOVDQU  (DI), X0
	VPSRLQ   $0x20, X0, X1
	VMOVDQU  (SI), X2
	VPSRLQ   $0x20, X2, X3
	VPMULUDQ X0, X2, X4
	VPMULUDQ X1, X2, X5
	VPSRLQ   $0x20, X4, X4
	VPADDQ   X5, X4, X4
	VPXOR    X5, X5, X5
	VPBLENDD $0x0a, X5, X4, X5
	VPSRLQ   $0x20, X4, X4
	VPMULUDQ X0, X3, X0
	VPADDQ   X0, X5, X0
	VPMULUDQ X1, X3, X1
	VPADDQ   X1, X4, X1
	VPSRLQ   $0x20, X0, X0
	VPADDQ   X0, X1, X0
	VMOVDQU  X0, (DI)
	VPMULUDQ X3, X0, X1
	VPSRLQ   $0x20, X0, X3
	VPMULUDQ X2, X3, X3
	VPADDQ   X3, X1, X1
	VPSLLQ   $0x20, X1, X1
	VPMULUDQ X2, X0, X0
	VPADDQ   X1, X0, X0
	VMOVDQU  X0, (SI)
	RET

// func VecAdd_AVX2_I64(x []uint64, y []uint64, z []uint64, u []uint64)
// Requires: AVX
TEXT ·VecAdd_AVX2_I64(SB), NOSPLIT, $0-96
	MOVQ    x_base+0(FP), DI
	MOVQ    y_base+24(FP), SI
	MOVQ    z_base+48(FP), DX
	MOVQ    u_base+72(FP), CX
	VMOVDQU (DI), X0
	VMOVDQU (SI), X1
	VPADDQ  X0, X1, X2
	VPADDQ  (DX), X2, X2
	VMOVDQU X2, (CX)
	VPAND   X0, X1, X3
	VPOR    X0, X1, X0
	VPANDN  X0, X2, X0
	VPOR    X3, X0, X0
	VPSRLQ  $0x3f, X0, X0
	VMOVDQU X0, (DX)
	RET
